version: '3'

services:
  %PROJECT_NAME%_www:
    container_name: %PROJECT_NAME%_www
    build: 
      context: ~/Docker/dockerfiles/wordpress/php7.3/apache/
    ports:
      - %PORT%:80
    volumes:
      # - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - %WP_ENV_DIR%/%PROJECT_NAME%:/var/www/html # Full wordpress project
      - %VOLUME% # Asset (Plugin or Theme) development
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: %PROJECT_NAME%
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: imprezautomka
    networks:
      - local_proxy

  %PROJECT_NAME%_wpcli:
    container_name: %PROJECT_NAME%_wpcli
    build: 
      context: ~/Docker/dockerfiles/wordpress/php7.3/cli/
    volumes:
      - %WP_ENV_DIR%/%PROJECT_NAME%:/var/www/html # Full wordpress project
      - %VOLUME% # Asset (Plugin or Theme) development
    networks:
      - local_proxy

networks:
  local_proxy:
    external: true
