version: '3'

services:
  %PROJECT_NAME%_www:
    container_name: %PROJECT_NAME%_www
    build: 
      context: ./
      args:
        - INSTALL_XDEBUG=true
        - INSTALL_PHPREDIS=false
        - INSTALL_IONCUBE=false
        - INSTALL_PHPINTL=false
        - INSTALL_EXIF=false
    ports:
      - %PORT%:80
    volumes:
      - %WP_ABSPATH%:/var/www/html # Full wordpress project
      - %VOLUME% # Asset (Plugin or Theme) development
      - ./.profiler:/run/profiler
    working_dir: /var/www/html/
    environment:
      XDEBUG_CONFIG: profiler_output_name=%PROJECT_NAME%.out.%p
    networks:
      - local_proxy

networks:
  local_proxy:
    external: true
